name: .NET Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish /p:EnvironmentName=Development --verbosity diagnostic
      

    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        target: ${{ secrets.FTP_REMOTE_DIR }}
        source: ./publish
        dangerous-clean-slate: true

    - name: Restart API Service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 188.138.101.4
        username: root
        password: tasqrRj#YR7n%pz
        script: |
          sudo systemctl restart HewarAPI.service
